require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/investments', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Investment. As you add validations to Investment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Investment.create! valid_attributes
      get investments_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      investment = Investment.create! valid_attributes
      get investment_url(investment)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_investment_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      investment = Investment.create! valid_attributes
      get edit_investment_url(investment)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Investment' do
        expect do
          post investments_url, params: { investment: valid_attributes }
        end.to change(Investment, :count).by(1)
      end

      it 'redirects to the created investment' do
        post investments_url, params: { investment: valid_attributes }
        expect(response).to redirect_to(investment_url(Investment.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Investment' do
        expect do
          post investments_url, params: { investment: invalid_attributes }
        end.to change(Investment, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post investments_url, params: { investment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested investment' do
        investment = Investment.create! valid_attributes
        patch investment_url(investment), params: { investment: new_attributes }
        investment.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the investment' do
        investment = Investment.create! valid_attributes
        patch investment_url(investment), params: { investment: new_attributes }
        investment.reload
        expect(response).to redirect_to(investment_url(investment))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        investment = Investment.create! valid_attributes
        patch investment_url(investment), params: { investment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested investment' do
      investment = Investment.create! valid_attributes
      expect do
        delete investment_url(investment)
      end.to change(Investment, :count).by(-1)
    end

    it 'redirects to the investments list' do
      investment = Investment.create! valid_attributes
      delete investment_url(investment)
      expect(response).to redirect_to(investments_url)
    end
  end
end
